# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stv2.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 440)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setProperty("pushButton_2", "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Processing = QtWidgets.QWidget()
        self.Processing.setObjectName("Processing")
        self.widget = QtWidgets.QWidget(self.Processing)
        self.widget.setGeometry(QtCore.QRect(10, 10, 753, 321))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_box = QtWidgets.QGroupBox(self.widget)
        self.input_box.setMinimumSize(QtCore.QSize(751, 61))
        self.input_box.setTitle(" Step 1: Input excel file ")
        self.input_box.setObjectName("input_box")
        self.browse_line = QtWidgets.QLineEdit(self.input_box)
        self.browse_line.setGeometry(QtCore.QRect(110, 28, 630, 26))
        self.browse_line.setText("")
        self.browse_line.setObjectName("browse_line")
        self.browse_btn = QtWidgets.QPushButton(self.input_box)
        self.browse_btn.setGeometry(QtCore.QRect(10, 27, 93, 28))
        self.browse_btn.setText("Browse")
        self.browse_btn.setDefault(True)
        self.browse_btn.setObjectName("browse_btn")
        self.verticalLayout.addWidget(self.input_box)
        self.load_box = QtWidgets.QGroupBox(self.widget)
        self.load_box.setTitle(" Step 2: Loading and selection ")
        self.load_box.setObjectName("load_box")
        self.load_btn = QtWidgets.QPushButton(self.load_box)
        self.load_btn.setGeometry(QtCore.QRect(10, 28, 93, 28))
        self.load_btn.setText("Load file")
        self.load_btn.setAutoDefault(False)
        self.load_btn.setDefault(True)
        self.load_btn.setObjectName("load_btn")
        self.comboBox = QtWidgets.QComboBox(self.load_box)
        self.comboBox.setGeometry(QtCore.QRect(540, 31, 200, 24))
        self.comboBox.setCurrentText("")
        self.comboBox.setPlaceholderText("")
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(self.load_box)
        self.label_2.setGeometry(QtCore.QRect(450, 35, 71, 16))
        self.label_2.setText("Select sheet")
        self.label_2.setObjectName("label_2")
        self.load_status = QtWidgets.QLabel(self.load_box)
        self.load_status.setGeometry(QtCore.QRect(120, 32, 311, 21))
        self.load_status.setText("")
        self.load_status.setObjectName("load_status")
        self.verticalLayout.addWidget(self.load_box)
        self.output_box = QtWidgets.QGroupBox(self.widget)
        self.output_box.setTitle(" Step 3: Output directory ")
        self.output_box.setObjectName("output_box")
        self.output_line = QtWidgets.QLineEdit(self.output_box)
        self.output_line.setGeometry(QtCore.QRect(110, 30, 630, 26))
        self.output_line.setText("")
        self.output_line.setObjectName("output_line")
        self.output_btn = QtWidgets.QPushButton(self.output_box)
        self.output_btn.setGeometry(QtCore.QRect(10, 29, 93, 28))
        self.output_btn.setText("Folder")
        self.output_btn.setDefault(True)
        self.output_btn.setObjectName("output_btn")
        self.verticalLayout.addWidget(self.output_box)
        self.process_block = QtWidgets.QGroupBox(self.widget)
        self.process_block.setTitle(" Step 4: Processing and Output ")
        self.process_block.setObjectName("process_block")
        self.process_btn = QtWidgets.QPushButton(self.process_block)
        self.process_btn.setGeometry(QtCore.QRect(10, 25, 93, 28))
        self.process_btn.setText("Process")
        self.process_btn.setDefault(True)
        self.process_btn.setObjectName("process_btn")
        self.process_progressBar = QtWidgets.QProgressBar(self.process_block)
        self.process_progressBar.setGeometry(QtCore.QRect(111, 27, 631, 25))
        self.process_progressBar.setProperty("value", 0)
        self.process_progressBar.setTextVisible(False)
        self.process_progressBar.setFormat("%p%")
        self.process_progressBar.setObjectName("process_progressBar")
        self.verticalLayout.addWidget(self.process_block)
        self.tabWidget.addTab(self.Processing, "Processing Utility")
        self.Converting = QtWidgets.QWidget()
        self.Converting.setObjectName("Converting")
        self.input_directory = QtWidgets.QGroupBox(self.Converting)
        self.input_directory.setGeometry(QtCore.QRect(10, 10, 751, 61))
        self.input_directory.setTitle(" Step 1: Input directory ")
        self.input_directory.setObjectName("input_directory")
        self.input_dir_path = QtWidgets.QLineEdit(self.input_directory)
        self.input_dir_path.setGeometry(QtCore.QRect(110, 24, 630, 26))
        self.input_dir_path.setText("")
        self.input_dir_path.setObjectName("input_dir_path")
        self.input_dir = QtWidgets.QPushButton(self.input_directory)
        self.input_dir.setGeometry(QtCore.QRect(10, 23, 93, 28))
        self.input_dir.setText("Input")
        self.input_dir.setDefault(True)
        self.input_dir.setObjectName("input_dir")
        self.select_file = QtWidgets.QGroupBox(self.Converting)
        self.select_file.setGeometry(QtCore.QRect(10, 80, 471, 251))
        self.select_file.setTitle(" Step 2: Select file(s) ")
        self.select_file.setObjectName("select_file")
        self.file_select = QtWidgets.QListWidget(self.select_file)
        self.file_select.setGeometry(QtCore.QRect(10, 29, 187, 213))
        self.file_select.setObjectName("file_select")
        self.file_select_scroll = QtWidgets.QScrollBar(self.select_file)
        self.file_select_scroll.setGeometry(QtCore.QRect(175, 30, 21, 211))
        self.file_select_scroll.setOrientation(QtCore.Qt.Vertical)
        self.file_select_scroll.setObjectName("file_select_scroll")
        self.file_convert = QtWidgets.QListWidget(self.select_file)
        self.file_convert.setGeometry(QtCore.QRect(275, 29, 187, 213))
        self.file_convert.setObjectName("file_convert")
        self.file_convert_scroll = QtWidgets.QScrollBar(self.select_file)
        self.file_convert_scroll.setGeometry(QtCore.QRect(440, 30, 21, 211))
        self.file_convert_scroll.setOrientation(QtCore.Qt.Vertical)
        self.file_convert_scroll.setObjectName("file_convert_scroll")
        self.splitter = QtWidgets.QSplitter(self.select_file)
        self.splitter.setGeometry(QtCore.QRect(210, 70, 51, 141))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.move_right_all = QtWidgets.QPushButton(self.splitter)
        self.move_right_all.setText(">>")
        self.move_right_all.setDefault(True)
        self.move_right_all.setObjectName("move_right_all")
        self.move_right = QtWidgets.QPushButton(self.splitter)
        self.move_right.setText(">")
        self.move_right.setDefault(True)
        self.move_right.setObjectName("move_right")
        self.move_left = QtWidgets.QPushButton(self.splitter)
        self.move_left.setText("<")
        self.move_left.setDefault(True)
        self.move_left.setObjectName("move_left")
        self.move_left_all = QtWidgets.QPushButton(self.splitter)
        self.move_left_all.setText("<<")
        self.move_left_all.setDefault(True)
        self.move_left_all.setObjectName("move_left_all")
        self.select_line = QtWidgets.QGroupBox(self.Converting)
        self.select_line.setGeometry(QtCore.QRect(490, 81, 270, 91))
        self.select_line.setTitle(" Step 3: Select Lines")
        self.select_line.setObjectName("select_line")
        self.textEdit = QtWidgets.QTextEdit(self.select_line)
        self.textEdit.setGeometry(QtCore.QRect(100, 40, 81, 31))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.select_line)
        self.label.setGeometry(QtCore.QRect(20, 40, 71, 31))
        self.label.setText("No. of lines")
        self.label.setObjectName("label")
        self.submit = QtWidgets.QPushButton(self.select_line)
        self.submit.setGeometry(QtCore.QRect(201, 40, 61, 28))
        self.submit.setText("Submit")
        self.submit.setDefault(True)
        self.submit.setObjectName("submit")
        self.convert_dir = QtWidgets.QGroupBox(self.Converting)
        self.convert_dir.setGeometry(QtCore.QRect(490, 180, 270, 121))
        self.convert_dir.setTitle(" Step 4: Converting files to selected lines ")
        self.convert_dir.setObjectName("convert_dir")
        self.convert_save_btn = QtWidgets.QPushButton(self.convert_dir)
        self.convert_save_btn.setGeometry(QtCore.QRect(86, 32, 81, 28))
        self.convert_save_btn.setText("Convert")
        self.convert_save_btn.setDefault(True)
        self.convert_save_btn.setObjectName("convert_save_btn")
        self.progressBar = QtWidgets.QProgressBar(self.convert_dir)
        self.progressBar.setGeometry(QtCore.QRect(16, 77, 241, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setFormat("%p%")
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.Converting, "Converting Utility")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 26))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionbtn_browse = QtWidgets.QAction(MainWindow)
        self.actionbtn_browse.setObjectName("actionbtn_browse")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setText("Exit")
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setText("About")
        self.actionAbout.setObjectName("actionAbout")
        self.menu_File.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.browse_btn)
        MainWindow.setTabOrder(self.browse_btn, self.load_btn)
        MainWindow.setTabOrder(self.load_btn, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.process_btn)
        MainWindow.setTabOrder(self.process_btn, self.output_line)
        MainWindow.setTabOrder(self.output_line, self.output_btn)
        MainWindow.setTabOrder(self.output_btn, self.browse_line)
        MainWindow.setTabOrder(self.browse_line, self.input_dir_path)
        MainWindow.setTabOrder(self.input_dir_path, self.input_dir)
        MainWindow.setTabOrder(self.input_dir, self.file_select)
        MainWindow.setTabOrder(self.file_select, self.move_right_all)
        MainWindow.setTabOrder(self.move_right_all, self.move_left_all)
        MainWindow.setTabOrder(self.move_left_all, self.convert_save_btn)
        MainWindow.setTabOrder(self.convert_save_btn, self.textEdit)
        MainWindow.setTabOrder(self.textEdit, self.file_convert)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sales Tax Automation Utility"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionbtn_browse.setText(_translate("MainWindow", "btn_browse"))
